name: "Terraform Deployment"
description: "Trigger a Terraform deployment for a specific resource"
title: "[Terraform] <SUBJECT>"
labels: ["terraform", "deployment"]
body:
  - type: input
    id: subject
    attributes:
      label: Subject
      placeholder: "e.g., Create EC2 instance"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - dev
        - staging
        - prod
    validations:
      required: true

  - type: input
    id: resource_path
    attributes:
      label: Path to Resource
      placeholder: "e.g., terraform/non-prod/us-west-2/dev/ec2"
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: Branch Name
      placeholder: "e.g., feature/my-ec2-change"
    validations:
      required: true

  # - name: Extract inputs from issue
  #   id: extract
  #   run: |
  #     echo "${{ github.event.issue.body }}" > issue.txt

  #     # Extract resource path
  #     path=$(grep -i 'Path to Resource:' issue.txt | cut -d':' -f2- | xargs)
  #     branch=$(grep -i 'Branch Name:' issue.txt | cut -d':' -f2- | xargs)

  #     # Validate path
  #     if [ -z "$path" ]; then
  #     echo "❌ Resource path is empty. Check issue formatting."
  #     exit 1
  #     fi

  #     echo "resource_path=$path" >> $GITHUB_OUTPUT
  #     echo "branch=$branch" >> $GITHUB_OUTPUT
